version: '3'
services:
  web1:
    image: nginx
    volumes:
      - ./web1/html:/usr/share/nginx/html:ro
  web2:
    image: nginx
    volumes:
          - ./web2/html:/usr/share/nginx/html:ro
  lb:
    image: nginx
    ports:
      - "8080:80"
    links:
      - web1
      - web2
    volumes:
      - ./lb/conf.d:/etc/nginx/conf.d:ro